_format_version: "3.0"

services:
  - name: mock-service
    url: http://mock-service:80
    routes:
      - name: mock-route
        paths:
          - /mock
    plugins:
      - name: rate-limiting
        config:
          minute: 5
          policy: local
      - name: ip-restriction
        config:
          deny:
            - "1.2.3.4"   # IP malveillante fictive
#      - name: request-termination
 #       config:
  #        status_code: 403
   #       message: "Access denied"  # Bloque IP si détectée malveillante
