%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "any"
    EXTERNAL_NET: "any"
  port-groups:
    HTTP_PORTS: "8000"
    SHELLCODE_PORTS: "!80"
    SSH_PORTS: "22"
    DNS_PORTS: "53"

logging:
  default-log-level: notice

default-log-dir: /var/log/suricata

defrag:
  memcap: 32mb
  hash-size: 65536
  trackers: 65535
  max-frags: 65535
  prealloc: yes
  timeout: 60

flow:
  memcap: 128mb
  hash-size: 65536
  prealloc: 10000
  emergency-recovery: 30

stream:
  memcap: 64mb
  checksum-validation: no
  inline: no
  reassembly:
    memcap: 256mb
    depth: 3mb
    toserver-chunk-size: 2560
    toclient-chunk-size: 2560

app-layer:
  protocols:
    http:
      enabled: yes
      libhtp:
        default-config:
          personality: IDS
          request-body-limit: 100kb
          response-body-limit: 100kb

# Listen on ALL interfaces
af-packet:
  - interface: eth0
    threads: auto
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
  - interface: lo
    threads: auto
    cluster-id: 98
    cluster-type: cluster_flow
    defrag: yes

rule-files:
  - /var/lib/suricata/rules/suricata.rules

detection-engine:
  - rule-reload: true
    rule-reload-policy: "auto"

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert:
            payload: yes
            payload-printable: yes
            metadata: yes
        - http:
            extended: yes
        - dns
        - flow

threading:
  set-cpu-affinity: no
  pattern: "worker"
